<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Estrada.ChromaDB.Repositories" Version="0.0.3-beta" />

    <PackageReference Include="Estrada.OllamaSharp.LameChain.SDK" Version="0.2.0-beta" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
  </ItemGroup>

</Project>
